export const REALITY = Object.freeze({
  PROPOSED: "PROPOSED",
  SIMULATED: "SIMULATED",
  LOCAL_VERIFIED: "LOCAL_VERIFIED",
  INTEGRATION_VERIFIED: "INTEGRATION_VERIFIED",
  EXTERNAL_VERIFIED: "EXTERNAL_VERIFIED",
  PRODUCTION_OPERATIONAL: "PRODUCTION_OPERATIONAL"
});

export const REALITY_ORDER = Object.freeze([
  REALITY.PROPOSED,
  REALITY.SIMULATED,
  REALITY.LOCAL_VERIFIED,
  REALITY.INTEGRATION_VERIFIED,
  REALITY.EXTERNAL_VERIFIED,
  REALITY.PRODUCTION_OPERATIONAL
]);

export function canPromote(current, next) {
  if (current === next) return true;

  const allowed = new Map([
    [REALITY.PROPOSED, new Set([REALITY.SIMULATED, REALITY.LOCAL_VERIFIED])],
    [REALITY.SIMULATED, new Set([REALITY.LOCAL_VERIFIED])],
    [REALITY.LOCAL_VERIFIED, new Set([REALITY.INTEGRATION_VERIFIED])],
    [REALITY.INTEGRATION_VERIFIED, new Set([REALITY.EXTERNAL_VERIFIED])],
    [REALITY.EXTERNAL_VERIFIED, new Set([REALITY.PRODUCTION_OPERATIONAL])],
    [REALITY.PRODUCTION_OPERATIONAL, new Set()]
  ]);

  return allowed.get(current)?.has(next) === true;
}